### ISSUE TITLE
Null Cmd field during pkger build

### ISSUE THREAD

**Issue by jonahweissman** [wojciechkepka/docker-api-rs#3]
- Crate version: source = "git+https://github.com/wojciechkepka/docker-api-rs?branch=master#8126914d06043da7c136d8cd4ee0ba0d9575575e"
- OS: Debian 10
- Output of running `docker version` on the command line:
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

I am trying to build a pkger recipe. The following is the output from `RUST_LOG=docker_api=trace,pkger=trace pkger build decide.rs`. (The logs from before the broken message are in the details tag.)

<details>
TRACE log_filter=docker_api=trace,pkger=trace
TRACE fmt_filter=FmtFilter {
    show_date: false,
    show_fields: false,
    hide_level: false,
    show_spans: false,
    delimiter: ", ",
}
TRACE opts=Opts {
    quiet: false,
    debug: false,
    trace: false,
    filter: None,
    config: None,
    command: Build(
        BuildOpts {
            recipes: [
                "decide.rs",
            ],
            simple: None,
            images: None,
            docker: None,
            all: false,
            no_sign: false,
        },
    ),
}
TRACE config_path=/home/melizalab/.pkger.yml
TRACE config=Configuration {
    recipes_dir: "/home/melizalab/lab_packages/recipes",
    output_dir: "/home/melizalab/lab_packages/packages",
    images_dir: Some(
        "/home/melizalab/lab_packages/images",
    ),
    docker: None,
    gpg_key: None,
    gpg_name: None,
    forward_ssh_agent: true,
}
TRACE images_state=RwLock {
    value: ImagesState {
        images: {},
        state_file: ".pkger.state",
    },
}
TRACE  loading, recipe=decide.rs
TRACE  using default docker uri
TRACE  creating new build context, id=pkger-decide-linux-armv7a-1626563777
INFO  running job, id=pkger-decide-linux-armv7a-1626563777
TRACE resolved_deps={
    "tar",
    "dpkg",
    "libczmq-dev",
    "git",
}
TRACE recipe=RecipeTarget {
    name: "decide",
    image_target: ImageTarget {
        image: "linux-armv7a",
        build_target: Deb,
        os: None,
    },
}
TRACE  checking if image should be rebuilt
DEBUG  building from scratch, image=linux-armv7a
TRACE  sending request POST unix://2f72756e2f646f636b65722e736f636b:0/v1.41/build?t=linux-armv7a%3Alatest, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=357
TRACE  got response 200 OK {"api-version": "1.41", "content-type": "application/json", "docker-experimental": "false", "ostype": "linux", "server": "Docker/20.10.7 (linux)", "date": "Sat, 17 Jul 2021 23:16:17 GMT", "transfer-encoding": "chunked"}, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=237
TRACE  got chunk b"{\"stream\":\"Step 1/1 : FROM dockcross/linux-armv7a:latest\"}\r\n", log.target="docker_api::docker", log.module_path="docker_api::docker", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/docker.rs", log.line=308
INFO  Step 1/1 : FROM dockcross/linux-armv7a:latest
TRACE  got chunk b"{\"stream\":\"\\n\"}\r\n", log.target="docker_api::docker", log.module_path="docker_api::docker", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/docker.rs", log.line=308
INFO  

TRACE  got chunk b"{\"stream\":\" ---\\u003e 9ffc72f820e7\\n\"}\r\n", log.target="docker_api::docker", log.module_path="docker_api::docker", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/docker.rs", log.line=308
INFO   ---> 9ffc72f820e7

TRACE  got chunk b"{\"aux\":{\"ID\":\"sha256:9ffc72f820e7826fc4939b458fcbe9945f17ca8032e9afe638a3bc6a0a90ca0e\"}}\r\n", log.target="docker_api::docker", log.module_path="docker_api::docker", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/docker.rs", log.line=308
TRACE  sending request POST unix://2f72756e2f646f636b65722e736f636b:0/v1.41/containers/create, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=357
TRACE  got response 201 Created {"api-version": "1.41", "content-type": "application/json", "docker-experimental": "false", "ostype": "linux", "server": "Docker/20.10.7 (linux)", "date": "Sat, 17 Jul 2021 23:16:17 GMT", "content-length": "88"}, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=237
TRACE  {"Id":"fb213ca2762463acbbb658acdb0c4356bfe5bdc8aae80d21ef7e16d86e537ff7","Warnings":[]}
, log.target="docker_api::docker", log.module_path="docker_api::docker", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/docker.rs", log.line=216
INFO  created container, id=fb213ca27624
TRACE  sending request POST unix://2f72756e2f646f636b65722e736f636b:0/v1.41/containers/fb213ca2762463acbbb658acdb0c4356bfe5bdc8aae80d21ef7e16d86e537ff7/start, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=357
TRACE  got response 204 No Content {"api-version": "1.41", "docker-experimental": "false", "ostype": "linux", "server": "Docker/20.10.7 (linux)", "date": "Sat, 17 Jul 2021 23:16:18 GMT"}, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=237
INFO  started container, id=fb213ca27624
TRACE stdout=true, stderr=true
INFO  collecting output
TRACE  sending request GET unix://2f72756e2f646f636b65722e736f636b:0/v1.41/containers/fb213ca2762463acbbb658acdb0c4356bfe5bdc8aae80d21ef7e16d86e537ff7/logs?stderr=true&stdout=true, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=357
TRACE  got response 200 OK {"api-version": "1.41", "docker-experimental": "false", "ostype": "linux", "server": "Docker/20.10.7 (linux)", "date": "Sat, 17 Jul 2021 23:16:18 GMT", "transfer-encoding": "chunked"}, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=237
TRACE stderr=
TRACE stdout=PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

DEBUG  parsed image info, os=Os {
    distribution: Debian,
    version: Some(
        "11",
    ),
}
TRACE  sending request GET unix://2f72756e2f646f636b65722e736f636b:0/v1.41/images/sha256:9ffc72f820e7826fc4939b458fcbe9945f17ca8032e9afe638a3bc6a0a90ca0e/json, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=357
TRACE  got response 200 OK {"api-version": "1.41", "content-type": "application/json", "docker-experimental": "false", "ostype": "linux", "server": "Docker/20.10.7 (linux)", "date": "Sat, 17 Jul 2021 23:16:18 GMT", "transfer-encoding": "chunked"}, log.target="docker_api::conn::transport", log.module_path="docker_api::conn::transport", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/conn/transport.rs", log.line=237
</details>
TRACE  {"Id":"sha256:9ffc72f820e7826fc4939b458fcbe9945f17ca8032e9afe638a3bc6a0a90ca0e","RepoTags":["dockcross/linux-armv7a:latest","linux-armv7a:latest"],"RepoDigests":["dockcross/linux-armv7a@sha256:7038d80ef3f6b2354f7accd55afbf3996886d2b11780197117f24c317e04bb6b"],"Parent":"","Comment":"","Created":"2021-07-08T23:45:18.844953662Z","Container":"8c69d3f715db948f79f821de64c22cf644fec8d4f27111f6f3cba3828929af86","ContainerConfig":{"Hostname":"8c69d3f715db","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin","CT_VERSION=62e9db247be34f8a4fa3bc116e60a1b15db62a97","XCC_PREFIX=/usr/xcc","CROSS_TRIPLE=arm-cortexa8_neon-linux-gnueabihf","CROSS_ROOT=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf","AS=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-as","AR=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-ar","CC=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-gcc","CPP=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-cpp","CXX=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-g++","LD=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-ld","FC=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-gfortran","QEMU_LD_PREFIX=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot","QEMU_SET_ENV=LD_LIBRARY_PATH=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/lib:/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot","DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-armv7a:latest","CMAKE_TOOLCHAIN_FILE=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/Toolchain.cmake","PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/","CROSS_COMPILE=arm-cortexa8_neon-linux-gnueabihf-","ARCH=arm"],"Cmd":["/bin/sh","-c","#(nop) ","ENV DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-armv7a:latest"],"Image":"sha256:39b4cbf40fccc5cd00c853bac846a03f817ba622f321bda574874c586e03d622","Volumes":null,"WorkingDir":"/work","Entrypoint":["/dockcross/entrypoint.sh"],"OnBuild":null,"Labels":{"org.label-schema.build-date":"2021-07-08T23:45:15Z","org.label-schema.name":"dockcross/linux-armv7a","org.label-schema.schema-version":"1.0","org.label-schema.vcs-ref":"94745ff","org.label-schema.vcs-url":"https://github.com/dockcross/dockcross","org.label-schema.version":"latest"}},"DockerVersion":"20.10.6+azure","Author":"Matt McCormick \"matt.mccormick@kitware.com\"","Config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin","CT_VERSION=62e9db247be34f8a4fa3bc116e60a1b15db62a97","XCC_PREFIX=/usr/xcc","CROSS_TRIPLE=arm-cortexa8_neon-linux-gnueabihf","CROSS_ROOT=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf","AS=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-as","AR=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-ar","CC=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-gcc","CPP=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-cpp","CXX=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-g++","LD=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-ld","FC=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-gfortran","QEMU_LD_PREFIX=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot","QEMU_SET_ENV=LD_LIBRARY_PATH=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/lib:/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot","DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-armv7a:latest","CMAKE_TOOLCHAIN_FILE=/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/Toolchain.cmake","PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/","CROSS_COMPILE=arm-cortexa8_neon-linux-gnueabihf-","ARCH=arm"],"Cmd":null,"Image":"sha256:39b4cbf40fccc5cd00c853bac846a03f817ba622f321bda574874c586e03d622","Volumes":null,"WorkingDir":"/work","Entrypoint":["/dockcross/entrypoint.sh"],"OnBuild":null,"Labels":{"org.label-schema.build-date":"2021-07-08T23:45:15Z","org.label-schema.name":"dockcross/linux-armv7a","org.label-schema.schema-version":"1.0","org.label-schema.vcs-ref":"94745ff","org.label-schema.vcs-url":"https://github.com/dockcross/dockcross","org.label-schema.version":"latest"}},"Architecture":"amd64","Os":"linux","Size":1752123680,"VirtualSize":1752123680,"GraphDriver":{"Data":{"LowerDir":"/var/lib/docker/overlay2/dfb6701fb424aa8e13a44884d06f18ad5e8da502e52d48e9a46e665e0a0e813e/diff:/var/lib/docker/overlay2/d4d7625a0fb57fc5eafd077582c0d318170caed8df4721bfa8a9a0e9c54d78d3/diff:/var/lib/docker/overlay2/ac18d3c8eaa30065955d5f52f40f477b199cd94cbcb78ee63e3c5c142e726418/diff:/var/lib/docker/overlay2/9acb7518e171538aed4fecb7b98caf4a5737db7bbda16fa1ef7a50b73e1cf3d0/diff:/var/lib/docker/overlay2/4a0acf2d89dc4ca09a2f645e8c39c0b78f5d0c73e4ff56937252faf47a1c947d/diff:/var/lib/docker/overlay2/8baa5fc7130848a9f3c3839c92980d568915b666c43c9207b7ec49536c376b68/diff:/var/lib/docker/overlay2/648ba137d7547490a20f6dc5bbbfb14a9b3c77f616d59961ae5e3212703ab293/diff:/var/lib/docker/overlay2/e01a035059b1151a887da26f5beff406e18ec1b20c0408dc1527d5cf16db982b/diff:/var/lib/docker/overlay2/a06ea16709b9a15f7d044a46a98c898a791523308f8b1c7f23a29726e259c400/diff:/var/lib/docker/overlay2/f9d72cd7b9153057b646a6a7248c14efda613d458d9bc471c00f692aa58dcdf4/diff:/var/lib/docker/overlay2/302db90f47968c35f9b794b5a5b60b473775173fd3ea69ff325876250f441598/diff:/var/lib/docker/overlay2/558dcfc88401a4fa96c0796b28bb0b7d619d54cb9d554de9296d9973d252e4c3/diff:/var/lib/docker/overlay2/851a06f233ad02594769ab1dbf20c480583a52761d3bfe0d2f052c90586ce6e9/diff:/var/lib/docker/overlay2/3d0399698f9626b3e47c0f9671fba8076053600452e88445d02f5b309753b75a/diff:/var/lib/docker/overlay2/8c21649ed8861551fad129c889203c83d15be2844a1d14fec3a443f48d331868/diff","MergedDir":"/var/lib/docker/overlay2/ff44dee124e2729d3a8cc061a61fd7a86a8d5139c3ccd0eb8e9c4aaf14ee6896/merged","UpperDir":"/var/lib/docker/overlay2/ff44dee124e2729d3a8cc061a61fd7a86a8d5139c3ccd0eb8e9c4aaf14ee6896/diff","WorkDir":"/var/lib/docker/overlay2/ff44dee124e2729d3a8cc061a61fd7a86a8d5139c3ccd0eb8e9c4aaf14ee6896/work"},"Name":"overlay2"},"RootFS":{"Type":"layers","Layers":["sha256:0fbfe9c110744441e16b6626ce11102c7a4c1ded556f9eb7796efd1756afb36b","sha256:d9c700da423e30f4dc0c4b83d8c108dec73cce4161bb696346801262af96d05e","sha256:b48007fb812e35e0e13d7c29c8d220b0ed72a8d1b7451414168385a7137e8d9c","sha256:641b724aa8e7b5203653feefe4bdf0e8214a79e4b141b04262ee54c0cbaa77c1","sha256:fc500140fca6eefa5e86cb496813a07ab56be5f7d876da316ed64c9498749e6e","sha256:1b92fdc6d96785feb3050f7d622695c190955b30d220a06c7dead3640e967341","sha256:c2e5a56f87987e67316f27d3df473a8edbc29d544c38db5c87dd66491107545e","sha256:238eef010cf4bef08482b8cb30c127d12d4f55109373f3fe4d6436ab86a1f25a","sha256:c5f1c82a20699369897189756f06cf731febc9ba20fedc479c04e44f0534b915","sha256:9b621342ba09af6872758162e7109a7303ef76f98c7cfe58f17aee9650d15e94","sha256:ac83272715286bcb5bc7c8b74f7a6e1d57585224fb9aa342e246ea6d04953e59","sha256:17c94c8cedd7f29a1f961be5f35835f8ad50c0a73085903e703669b46e5dab9a","sha256:f31eba605364a3a423576378b2d4b1f6a9d1ae29820e5f5faab09ba3c717e574","sha256:e37f09d5f0ff0cbace1da2c5f4ca37a86af5ce257eeeee7102b8993e552cbe26","sha256:743f81105424d88afc04c2d55d7ec3b6ca69f1b41339099bf77fb2b490d86e33","sha256:139e5db22604651a516488a0fdcb48cfb134d6a4ca22ea4251074632a262e8ed"]},"Metadata":{"LastTagTime":"2021-07-17T19:16:17.864046973-04:00"}}
, log.target="docker_api::docker", log.module_path="docker_api::docker", log.file="/home/melizalab/.cargo/git/checkouts/docker-api-rs-9127327c5ec9cacd/8126914/src/docker.rs", log.line=180
ERROR  job failed, id=pkger-decide-linux-armv7a-1626563777, reason=invalid type: null, expected a sequence at line 1 column 4312, duration=0.5375528s
TRACE  saving images state

---

It seems like the problem is that the `Cmd` field has a value of "null",  but I don't understand the structure of the code enough to know where that might have come from.

**Comment by wojciechkepka** [comment]
Thank you for the report! #4 should fix the issues with deserialization.
